server {
    listen 80;
    server_name trydal.io *.trydal.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name trydal.io *.trydal.io;

    ssl_certificate     /etc/nginx/ssl/trydal.io.crt;
    ssl_certificate_key /etc/nginx/ssl/trydal.io.key;

    root /var/www/trydal.io;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /docs {
        alias /var/www/trydal.io/docs-source/site/;
        index index.html;
        try_files $uri $uri/ /docs/index.html;
    }
}
